org.spongycastle.cert.jcajce.JcaX509CertificateConverter$ExCertificateException extends java.security.cert.CertificateException
private java.lang.Throwable cause
final org.spongycastle.cert.jcajce.JcaX509CertificateConverter this$0
    public void <init>(org.spongycastle.cert.jcajce.JcaX509CertificateConverter, java.lang.String, java.lang.Throwable)
    {
        org.spongycastle.cert.jcajce.JcaX509CertificateConverter$ExCertificateException r0;
        org.spongycastle.cert.jcajce.JcaX509CertificateConverter $r1;
        java.lang.String $r2;
        java.lang.Throwable $r3;

        r0 := @this: org.spongycastle.cert.jcajce.JcaX509CertificateConverter$ExCertificateException;

        $r1 := @parameter0: org.spongycastle.cert.jcajce.JcaX509CertificateConverter;

        $r2 := @parameter1: java.lang.String;

        $r3 := @parameter2: java.lang.Throwable;

        r0.<org.spongycastle.cert.jcajce.JcaX509CertificateConverter$ExCertificateException: org.spongycastle.cert.jcajce.JcaX509CertificateConverter this$0> = $r1;

        specialinvoke r0.<java.security.cert.CertificateException: void <init>(java.lang.String)>($r2);

        r0.<org.spongycastle.cert.jcajce.JcaX509CertificateConverter$ExCertificateException: java.lang.Throwable cause> = $r3;

        return;
    }
    public java.lang.Throwable getCause()
    {
        org.spongycastle.cert.jcajce.JcaX509CertificateConverter$ExCertificateException r0;
        java.lang.Throwable r1;

        r0 := @this: org.spongycastle.cert.jcajce.JcaX509CertificateConverter$ExCertificateException;

        r1 = r0.<org.spongycastle.cert.jcajce.JcaX509CertificateConverter$ExCertificateException: java.lang.Throwable cause>;

        return r1;
    }
