org.spongycastle.util.test.TestFailedException extends java.lang.RuntimeException
private org.spongycastle.util.test.TestResult _result
    public void <init>(org.spongycastle.util.test.TestResult)
    {
        org.spongycastle.util.test.TestFailedException r0;
        org.spongycastle.util.test.TestResult $r1;

        r0 := @this: org.spongycastle.util.test.TestFailedException;

        $r1 := @parameter0: org.spongycastle.util.test.TestResult;

        specialinvoke r0.<java.lang.RuntimeException: void <init>()>();

        r0.<org.spongycastle.util.test.TestFailedException: org.spongycastle.util.test.TestResult _result> = $r1;

        return;
    }
    public org.spongycastle.util.test.TestResult getResult()
    {
        org.spongycastle.util.test.TestFailedException r0;
        org.spongycastle.util.test.TestResult r1;

        r0 := @this: org.spongycastle.util.test.TestFailedException;

        r1 = r0.<org.spongycastle.util.test.TestFailedException: org.spongycastle.util.test.TestResult _result>;

        return r1;
    }
